name: "Build publish and deploy"
description: "Build project, publish to registry and deploy into the cluster"
inputs:
  workspace:
    description: "Workspace used by terraform"
    required: true
    default: "default"
  cloud-path:
    required: true
    description: "Cloud application path"
  prefix-tag:
    required: false
    description: "Prefixed used in alpha for the tag image"
    default: ""
  gcp-credentials:
    required: true
    description: "GCP services account credentials"
  environment:
    required: false
    description: "Application environment (integration / production)"
    default: "integration"

runs:
  using: "composite"
  steps:
    - name: Get tag
      shell: bash
      id: get_tag
      run: echo ::set-output name=TAG::$PREFIX_TAG$(echo $GITHUB_REF | cut -d / -f 3)
      env:
        PREFIX_TAG: ${{ inputs.prefix-tag }}

    - name: Terraform init and fmt
      shell: bash
      working-directory: ${{ inputs.cloud-path }}
      run: |
        terraform init
        echo "Checking if terraform workspace exists..."
        if [[ $(terraform workspace list) =~ "${{ inputs.workspace }}" ]]; then
          echo "The ${{ inputs.workspace }} workspace exists"
          terraform workspace select ${{ inputs.workspace }}
        else
          echo "The ${{ inputs.workspace }} workspace does not exist"
          terraform workspace new ${{ inputs.workspace }}
        fi
        terraform fmt
      env:
        GOOGLE_CREDENTIALS: ${{ inputs.gcp-credentials }}

    - name: Terraform apply
      shell: bash
      working-directory: ${{ inputs.cloud-path }}
      run: |
        terraform apply -auto-approve \
        --var app_version=$TAG \
        --var hash_id=$SHA \
        --var 'service_account_key=${GOOGLE_CREDENTIALS}'
      env:
        TAG: ${{ inputs.environment }}
        SHA: ${{ github.sha }}
        GOOGLE_CREDENTIALS: ${{ inputs.gcp-credentials }}
