name: Integration CD for QAnightly

on:
  push:
    branches:
      - develop

env:
  GCLOUD_NAMESPACE: 'prestashop-cloud-integration'
  PROJECT_NAME: 'qanightlyresults'
  TF_VERSION: '1.3.7'
  APP_PATH: ./
  APP_CLOUD_PATH: "./terraform/envs/integration"

jobs:
  integration_deployment:
    name: Deploy (integration)
    runs-on: ubuntu-latest
    concurrency: integration-cd

    steps:
      - name: Setting up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 20

      - name: Auth GCP
        uses: ./.github/actions/auth-gcp
        with:
          gcp-credentials: ${{ secrets.INTEGRATION_GOOGLE_APPLICATION_CREDENTIALS }}
          cluster-name: "test-cluster-1"

      - name: Build API app 👷
        uses: ./.github/actions/build
        with:
          project: ${{ env.PROJECT_NAME }}
          gcp-credentials: ${{ secrets.INTEGRATION_GOOGLE_APPLICATION_CREDENTIALS }}
          gcp-namespace: ${{ env.GCLOUD_NAMESPACE }}
          app-path: ${{ env.APP_PATH }}
          environment: "integration"

      # - name: Deploy app 🚚
      #   uses: ./.github/actions/deploy
      #   with:
      #     workspace: default
      #     cloud-path: ${{ env.APP_CLOUD_PATH }}
      #     gcp-credentials: ${{ secrets.INTEGRATION_GOOGLE_APPLICATION_CREDENTIALS }}
      #     gcp-namespace: ${{ env.GCLOUD_NAMESPACE }}
      #     environment: "integration"
