name: Integration CD for QAnightly

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

env:
  DISTRIBUTION_APP: "qanightly"
  LABELS: ${{toJSON(github.event.pull_request.labels)}}
  BUCKET_PRESTABULLE: ${{ secrets.BUCKET_PRESTABULLE }}

jobs:
  integration_deployment:
    name: Deploy (integration)
    runs-on: ubuntu-latest
    concurrency: integration-cd
    environment: integration
    if: contains(github.event.pull_request.labels.*.name, 'prestabulle1') ||
      contains(github.event.pull_request.labels.*.name, 'prestabulle2') ||
      contains(github.event.pull_request.labels.*.name, 'prestabulle3')

    steps:
      - name: Checkout the repository 🎁
        uses: actions/checkout@v3

      - name: Authenticating to GCP ⚙️
        uses: google-github-actions/auth@v1
        with:
          project_id: ${{ secrets.GCP_RUN_PROJECT_ID }}
          credentials_json: ${{ secrets.INTEGRATION_GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Setting up Cloud SDK ⚙️
        uses: google-github-actions/setup-gcloud@v1

      - name: Managing labels 🏷️
        run: /bin/bash .github/scripts/manage-labels.sh

      - name: Setting up the Bulle variable for later 💬
        run: echo "BULLE=$BULLE$(echo $LABELS > labels.json && cat labels.json | jq -r '.[]|.name'|grep prestabulle)" >> $GITHUB_OUTPUT
        id: get_bulle

      - name: Get branch name
        id: branch
        uses: tj-actions/branch-names@v5.1

      - name: Trigger CI / CD
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: integration-cd.yml
          repo: PrestaShopCorp/qanightlyresults-cd
          inputs: '{ "branch": "${{ steps.branch.outputs.current_branch }}", "bulle": "${{ steps.get_bulle.outputs.BULLE }}", "project": "api-nightly", "repository": "PrestaShop/QANightlyResults"}'
          token: ${{ secrets.TERRAFORM_ACCESS_TOKEN }}
          ref: 'refs/heads/feat/migration-nightly'