name: Preproduction CD for QAnightly

on:
  push:
    branches:
# I see that they got only 2 environments, I supposed they are deploying only on preprod and production. In my mind develop = peprod.
      - ops/ci-cd-rework

env:
# GCLOUD_NAMESPACE need to be changed, we make the decision to change cluster project ? 
  GCLOUD_NAMESPACE: 'prestashop-cloud-integration'
  PROJECT_NAME: 'qanightlyresults'
  TF_VERSION: '1.3.7'
  APP_PATH: ./

jobs:
  preproduction_deployment:
    name: Deploy (preproduction)
    runs-on: ubuntu-latest
    concurrency: preprod-cd

    steps:
    - name: Setting up Terraform
      uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 20

      # - name: Auth GCP
      #   uses: ./.github/actions/auth-gcp
      #   with:
      #     gcp-credentials: ${{ secrets.PREPROD_GOOGLE_APPLICATION_CREDENTIALS }}
      #     cluster-name: "test-cluster-1" # need to be changed by the new cluster

      # - name: Build API app 👷
      #   uses: ./.github/actions/build
      #   with:
      #     project: ${{ env.PROJECT_NAME }}
      #     gcp-credentials: ${{ secrets.PREPROD_GOOGLE_APPLICATION_CREDENTIALS }}
      #     gcp-namespace: ${{ env.GCLOUD_NAMESPACE }}
      #     app-path: ${{ env.APP_PATH }}
      #     environment: "preproduction"
