name: production CD for QAnightly

on:
  release:
    types: [released]

env:
  DISTRIBUTION_APP: "qanightly"

jobs:
  production_deployment:
    name: Deploy (production)
    runs-on: ubuntu-latest
    environment: production
    concurrency: production-cd

    steps:
      - name: Checkout the repository 🎁
        uses: actions/checkout@v3

      - name: Authenticating to GCP ⚙️
        uses: google-github-actions/auth@v1
        with:
          project_id: ${{ secrets.GCP_RUN_PROJECT_ID }}
          credentials_json: ${{ secrets.PRODUCTION_GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Setting up Cloud SDK ⚙️
        uses: google-github-actions/setup-gcloud@v1

      - name: Get branch name
        id: branch
        uses: tj-actions/branch-names@v5.1

      - name: Trigger CI / CD
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: production-cd.yml
          repo: PrestaShopCorp/qanightlyresults-cd
          inputs: '{ "branch": "${{ steps.branch.outputs.current_branch }}", "project": "nightly", "repository": "PrestaShop/nightly-board"}'
          token: ${{ secrets.TERRAFORM_ACCESS_TOKEN }}
          ref: 'refs/heads/main'