name: Production CD for QAnightly

on:
  push:
    branches:
      - master

env:
  GCLOUD_NAMESPACE: 'prestashop-cloud-production'
  PROJECT_NAME: 'qanightlyresults'
  TF_VERSION: '1.3.7'
  APP_PATH: ./

jobs:
  production_deployment:
    name: Deploy (production)
    runs-on: ubuntu-latest
    concurrency: production-cd

    steps:
      - name: Setting up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 20

      - name: Auth GCP
        uses: ./.github/actions/auth-gcp
        with:
          gcp-credentials: ${{ secrets.PRODUCTION_GOOGLE_APPLICATION_CREDENTIALS }}
          cluster-name: "production-cluster-1"

      # - name: Tag production images
      #   shell: bash
      #   run: gcloud container images add-tag $REGISTRY_SERVER/$GCLOUD_NAMESPACE/$PROJECT_NAME/$PROJECT_NAME:integration $REGISTRY_SERVER/$GCLOUD_NAMESPACE/$PROJECT_NAME/$PROJECT_NAME:production
      #   env:
      #     REGISTRY_SERVER: "gcr.io"
